import React from "react";
import ProjectCard from "../components/ProjectCard";
import { BiBriefcase, BiPrinter } from "react-icons/bi";
import GlassSection from "../components/GlassSection";

const Applications = () => {
  return (
    <div>
      <GlassSection title="web applications." className="w-full">
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          {" "}
          <ProjectCard
            icon={<BiPrinter />}
            title="InstaPrint | Thesis"
            description="InstaPrint is a Flask-based print service with Arduino integration. It automates file uploads, calculates printing costs, and supports GCash/coin-based payments. Built for print shops needing real-time queue management."
            tags={[
              "Flask",
              "Python",
              "Arduino",
              "GSM Module",
              "GCash Integration",
            ]}
          />
          <ProjectCard
            icon={<BiBriefcase />}
            title="Educast"
            description="Educast is a React and Supabase-based podcast web app that allows professors to share unlisted or public YouTube lectures with students. Students can comment and view embedded media. Includes role-based access and authentication."
            tags={["ReactJS", "Typescript", "Supabase", "Postgre SQL"]}
            extraLink="https://educast.onrender.com/auth"
            extraLinkLabel="Go to Educast" // default is "Visit"
          />
          <ProjectCard
            icon={<BiBriefcase />}
            title="API Projects Compilation"
            description="A collection of web apps using free APIs (e.g. weather, jokes, dictionary). Shows REST API integration and dynamic UI rendering with JavaScript."
            tags={["HTML", "CSS", "Javascript"]}
            extraLink="https://shinaylim.github.io/api-projects-compilation/"
            extraLinkLabel="LIve Demo"
          />
          <ProjectCard
            icon={<BiBriefcase />}
            title="JavaScript Games Compilation"
            description="A showcase of mini-games built using pure JavaScript, such as Tic Tac Toe and Memory Match. Focus on logic, interactivity, and DOM control."
            tags={["HTML", "CSS", "Javascript"]}
            extraLink="https://shinaylim.github.io/js-games-compilation/"
            extraLinkLabel="Live Demo"
          />
          <ProjectCard
            icon={<BiBriefcase />}
            title="Luksong Baka 2 (GitHub)"
            description="A 2D side-scrolling game inspired by the Filipino game Luksong Baka. Built with Unity Game Engine 2021.3.16 and C# (.NET Standard 2.1) for local multiplayer fun. "
            tags={["Unity", "C#"]}
            extraLink="https://siegfredlorelle.itch.io/luksong-baka"
            extraLinkLabel="Play our game"
          />
          <ProjectCard
            icon={<BiBriefcase />}
            title="2x2 Rubik's Solver App"
            description="A mobile app that guides users in solving a 2x2 Rubik's Cube. Users can tap and color a virtual cube to match their real one, then follow step-by-step moves generated by the solver."
            tags={["Cordova", "HTML", "CSS", "Javascript"]}
            extraLink="https://cet4-proposal.vercel.app/"
            extraLinkLabel="Live Demo"
          />
        </div>
      </GlassSection>
    </div>
  );
};

export default Applications;
